# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Haram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'NMapsMap'
  pod 'Elliotable', '1.2.5'
  pod 'AcknowList', '3.1.0'
  pod 'Firebase/Analytics', '~> 10.23.1'
  pod 'Firebase/Crashlytics', '10.23.1'

  use_frameworks!
  pod 'ZXingObjC', '~> 3.6.4'
  # Pods for Haram

  target 'HaramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HaramUITests' do
    # Pods for testing
  end

end
