# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Haram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'NMapsMap'
  pod 'Elliotable'
  pod 'AcknowList'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  use_frameworks!
  pod 'ZXingObjC', '~> 3.6.4'
  # Pods for Haram

  target 'HaramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HaramUITests' do
    # Pods for testing
  end

end
