# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "build app and upload to testflight"
  lane :beta do
    get_certificates
    get_provisioning_profile
    increment_build_number(
        build_number: latest_testflight_build_number + 1
    )
    build_app(
      configuration: "Debug"
    )
    upload_to_testflight
    slack(
      message: "Testflight 배포 성공",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end

  lane :tests do
scan(scheme: "Haram",
       slack_url: "https://hooks.slack.com/services/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")
  end

  error do |lane, exception, options|
    slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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",
    )
  end
end
