# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run SeongseoAlarmy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Haram
      run: |
        pod install --repo-update --clean-install --project-directory=Haram/
        xcodebuild clean test -workspace Haram/Haram.xcworkspace -scheme Haram -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
