# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run SeongseoAlarmy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Fastlane을 실행하기 위한 Ruby 버전 설정

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install

    - name: Run Fastlane beta lane
      run: bundle exec fastlane beta
